"""create used_tokens table

Revision ID: 0058a8dfd3dc
Revises: 77f35a42bf6e
Create Date: 2026-06-02 05:55:48.499463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0058a8dfd3dc'
down_revision: Union[str, Sequence[str], None] = '77f35a42bf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_used_tokens_id'), 'used_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_used_tokens_token'), 'used_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_tokens_token'), table_name='used_tokens')
    op.drop_index(op.f('ix_used_tokens_id'), table_name='used_tokens')
    op.drop_table('used_tokens')
    # ### end Alembic commands ###
